import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart';

class FirebaseService {
  static final FirebaseService _instance = FirebaseService._internal();

  factory FirebaseService() {
    return _instance;
  }

  FirebaseService._internal();

  static late final FirebaseApp app;

  static Future<void> initialize() async {
    final opts = DefaultFirebaseOptions.currentPlatform;

    // Basic validation to catch placeholder configs generated by the CLI
    bool isPlaceholder(String? v) => v == null || v.startsWith('YOUR_') || v.contains('YOUR_');
    if (isPlaceholder(opts.apiKey) || isPlaceholder(opts.projectId) || isPlaceholder(opts.appId)) {
      throw FirebaseConfigException(
          'Firebase configuration appears to contain placeholder values.\n'
          'Please replace the placeholders in lib/services/firebase_options.dart with your Firebase project config or run `flutterfire configure`.');
    }

    try {
      app = await Firebase.initializeApp(options: opts);
      // Log the initialized Firebase app for debugging
      // ignore: avoid_print
      print('Firebase initialized with app: ${app.name}, projectId: ${app.options.projectId}');
      // Set Firestore settings
      FirebaseFirestore.instanceFor(app: app).settings = const Settings(
        persistenceEnabled: true,
        cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
      );
    } catch (e) {
      throw FirebaseConfigException('Firebase initialization failed: $e');
    }
  }

  // Auth Singleton
  static FirebaseAuth get auth => FirebaseAuth.instanceFor(app: app);

  // Firestore Singleton
  static FirebaseFirestore get firestore => FirebaseFirestore.instanceFor(app: app);

  // Get current user
  static User? get currentUser => auth.currentUser;

  // Check if user is logged in
  static bool get isLoggedIn => currentUser != null;
}

class FirebaseConfigException implements Exception {
  final String message;
  FirebaseConfigException(this.message);
  @override
  String toString() => message;
}
